# Generated by Django 5.2.4 on 2025-07-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Administrador",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "nome",
                    models.CharField(max_length=255, verbose_name="Nome Completo"),
                ),
                ("telefone", models.CharField(max_length=20, verbose_name="Telefone")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                ("senha", models.CharField(max_length=128, verbose_name="Senha Hash")),
            ],
            options={
                "verbose_name": "Conta de Administrador",
                "verbose_name_plural": "Contas de Administradores",
            },
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "nome",
                    models.CharField(max_length=255, verbose_name="Nome Completo"),
                ),
                ("telefone", models.CharField(max_length=20, verbose_name="Telefone")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                ("senha", models.CharField(max_length=128, verbose_name="Senha Hash")),
                (
                    "cpf",
                    models.CharField(max_length=14, unique=True, verbose_name="CPF"),
                ),
                ("endereco", models.TextField(verbose_name="Endereço Completo")),
            ],
            options={
                "verbose_name": "Conta de Cliente",
                "verbose_name_plural": "Contas de Clientes",
            },
        ),
        migrations.CreateModel(
            name="Funcionario",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "nome",
                    models.CharField(max_length=255, verbose_name="Nome Completo"),
                ),
                ("telefone", models.CharField(max_length=20, verbose_name="Telefone")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                ("senha", models.CharField(max_length=128, verbose_name="Senha Hash")),
                ("cargo", models.CharField(max_length=100, verbose_name="Cargo")),
            ],
            options={
                "verbose_name": "Conta de Funcionário",
                "verbose_name_plural": "Contas de Funcionários",
            },
        ),
    ]
