# Generated by Django 5.2.4 on 2025-07-13 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("animal", "0001_initial"),
        ("contas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agendamento",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "data_hora",
                    models.DateTimeField(verbose_name="Data e Hora do Agendamento"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pendente", "Pendente"),
                            ("Confirmado", "Confirmado"),
                            ("Cancelado", "Cancelado"),
                            ("Concluído", "Concluído"),
                        ],
                        default="Pendente",
                        max_length=50,
                        verbose_name="Status do Agendamento",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agendamentos_admin",
                        to="contas.administrador",
                        verbose_name="Administrador que Registrou",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agendamentos_cliente",
                        to="contas.cliente",
                        verbose_name="Cliente do Agendamento",
                    ),
                ),
                (
                    "funcionario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agendamentos_funcionario",
                        to="contas.funcionario",
                        verbose_name="Funcionário Responsável",
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agendamentos",
                        to="animal.pet",
                        verbose_name="Pet Agendado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agendamento",
                "verbose_name_plural": "Agendamentos",
                "ordering": ["data_hora"],
            },
        ),
    ]
