# Generated by Django 5.2.4 on 2025-07-13 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pet",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=255, verbose_name="Nome do Pet")),
                (
                    "tipo",
                    models.CharField(
                        max_length=100,
                        verbose_name="Tipo (Ex: Cachorro, Gato, Pássaro)",
                    ),
                ),
                (
                    "sexo",
                    models.CharField(
                        max_length=10, verbose_name="Sexo (Ex: Macho, Fêmea)"
                    ),
                ),
                (
                    "peso",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Peso (kg)"
                    ),
                ),
                (
                    "raca",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Raça"
                    ),
                ),
                (
                    "temperamento",
                    models.TextField(
                        blank=True, null=True, verbose_name="Temperamento do Pet"
                    ),
                ),
                (
                    "castracao",
                    models.BooleanField(default=False, verbose_name="Castrado(a)?"),
                ),
                (
                    "observacoes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observações Adicionais"
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pets",
                        to="contas.cliente",
                        verbose_name="Dono do Pet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pet",
                "verbose_name_plural": "Pets",
                "ordering": ["nome"],
            },
        ),
    ]
